name: first

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

          - name: checkout repo
            uses: actions/checkout@v4

          - name: welcome msg
            run: echo "first github actions"

          - name: node Intall
            uses: actions/setup-node@v4
            with:
              node-version: "18"

          - name : install dep
            run: npm install

          - name: listing files
            run: ls -ltra

          - name: opening server.js
            run: cat server.js

          - name: Start server (background)
            run: node server.js &

          - name: Test server
            run: |
             curl https://loca.lt/mytunnelpassword
             sleep 3000
        