name: interactive-debug
on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30  # Add timeout
        with:
          limit-access-to-actor: true  # Only allow the workflow trigger to connect