name: Modify AnkiDroid NoteEditorFragment

on: push

jobs:
  modify-ankidroid:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone AnkiDroid repository
      run: |
        git clone https://github.com/ankidroid/Anki-Android.git
        cd Anki-Android
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.0
        
    - name: Backup original file
      run: |
        cd Anki-Android
        cp AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt.backup
        
    - name: Modify NoteEditorFragment.kt
      run: |
        cd Anki-Android
        
        # Create the modified function content
        cat > modified_function.kt << 'EOF'
        private fun closeNoteEditor(intent: Intent = Intent()) {
            val result: Int = if (changed) Activity.RESULT_OK else RESULT_CANCELED
            
            if (reloadRequired) {
                intent.putExtra(RELOAD_REQUIRED_EXTRA_KEY, true)
            }
            if (changed) {
                intent.putExtra(NOTE_CHANGED_EXTRA_KEY, true)
                
                lifecycleScope.launch {
                    val textToSend = editFields.joinToString("\n") { it.text.toString() }
                    
                    try {
                        withContext(Dispatchers.IO) {
                            val client = OkHttpClient()
                            
                            val requestBody = """
                                {
                                  "contents": [
                                    {
                                      "parts": [
                                        { "text": "${textToSend.replace("\"", "\\\"")}" }
                                      ]
                                    }
                                  ]
                                }
                            """.trimIndent()
                            
                            val request = Request.Builder()
                                .url("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyAeNoHzS6zrvBtzYVfMDGiFwUtLYAipczU")
                                .post(requestBody.toRequestBody("application/json".toMediaType()))
                                .build()
                            
                            client.newCall(request).execute().use { response ->
                                val body = response.body?.string()
                                if (!response.isSuccessful || body == null) {
                                    throw IOException("Unexpected code $response\nBody: $body")
                                }
                                
                                val text = JSONObject(body)
                                    .getJSONArray("candidates")
                                    .getJSONObject(0)
                                    .getJSONObject("content")
                                    .getJSONArray("parts")
                                    .getJSONObject(0)
                                    .getString("text")
                                
                                withContext(Dispatchers.Main) {
                                    Toast.makeText(
                                        requireContext(),
                                        "Gemini: $text",
                                        Toast.LENGTH_LONG
                                    ).show()
                                }
                            }
                        }
                    } catch (e: Exception) {
                        e.printStackTrace()
                        withContext(Dispatchers.Main) {
                            Toast.makeText(requireContext(), "Gemini error: ${e.message}", Toast.LENGTH_LONG).show()
                        }
                    }
                }
            }
            setResult(result, intent)
            requireActivity().finish()
        }
        EOF
        
        # Use Python to replace the function safely
        python3 << 'EOF'
        import re

        # Read original file
        with open('AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt', 'r') as f:
            content = f.read()

        # Read new function
        with open('modified_function.kt', 'r') as f:
            new_function = f.read()

        # Regex: replace from function start until finish() call
        pattern = r'private\s+fun\s+closeNoteEditor[\\s\\S]*?requireActivity\\(\\)\\.finish\\(\\)'

        modified_content = re.sub(pattern, new_function.strip(), content, flags=re.DOTALL)

        with open('AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt', 'w') as f:
            f.write(modified_content)

        print("Function replacement completed")
        EOF
        
    - name: Add required imports
      run: |
        cd Anki-Android
        python3 << 'EOF'
        import re

        path = 'AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt'
        with open(path, 'r') as f:
            content = f.read()

        required_imports = [
            'import okhttp3.OkHttpClient',
            'import okhttp3.Request',
            'import okhttp3.RequestBody.Companion.toRequestBody',
            'import okhttp3.MediaType.Companion.toMediaType',
            'import kotlinx.coroutines.Dispatchers',
            'import kotlinx.coroutines.withContext',
            'import kotlinx.coroutines.launch',
            'import androidx.lifecycle.lifecycleScope',
            'import android.widget.Toast',
            'import org.json.JSONObject',
            'import java.io.IOException',
            'import android.app.Activity'
        ]

        package_match = re.search(r'^package\\s+[^\\n]+', content, re.MULTILINE)
        if package_match:
            insert_pos = package_match.end()
            missing = [imp for imp in required_imports if imp not in content]
            if missing:
                content = content[:insert_pos] + '\n\n' + '\n'.join(missing) + content[insert_pos:]
                with open(path, 'w') as f:
                    f.write(content)
                print(f"Added {len(missing)} imports")
            else:
                print("All imports already exist")
        else:
            print("Package not found")
        EOF
        
    - name: Add OkHttp dependency to build.gradle
      run: |
        cd Anki-Android
        if ! grep -q "implementation.*okhttp3" AnkiDroid/build.gradle; then
            sed -i '/dependencies {/a\    implementation "com.squareup.okhttp3:okhttp:4.12.0"' AnkiDroid/build.gradle
            echo "Added OkHttp dependency"
        else
            echo "OkHttp dependency already exists"
        fi
        
    - name: Verify changes
      run: |
        cd Anki-Android
        echo "=== Modified closeNoteEditor ==="
        grep -A 40 "private fun closeNoteEditor" AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
        
        echo -e "\n=== Build.gradle check ==="
        grep -n "okhttp" AnkiDroid/build.gradle || echo "OkHttp dependency not found"
        
    - name: Build Debug APK
      run: |
        cd Anki-Android
        ./gradlew assembleDebug --stacktrace
        
    - name: Check for APK
      run: |
        cd Anki-Android/AnkiDroid/build/outputs/apk/debug
        ls -lh

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ankidroid-debug-apk
        path: Anki-Android/AnkiDroid/build/outputs/apk/debug/*.apk
