name: third

on: 
  schedule:
    - cron: '*/5 * * * *'

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "hellowrodl"
          ls - ltra
          echo "used helloword"