name: third

on: 
  push:
  # schedule:
    # - cron: '*/5 * * * *'

env:
  sleep: 200

jobs:
  job_1:
    strategy:
      matrix:
        arr : [0,1,2,3]
        arr2: [4,5]
      

    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "${{matrix.arr}}"
          echo "${{matrix.arr2}}"
          echo "$((${{matrix.arr}}*${{matrix.arr2}}))"
           
